begin rework 18/19
latex4ei/Algorithmen-und-Datenstrukturen pull request #1
Opened 2019-07-13 22:54 UTC by HappyDayHunter

Check the content, not final yet
TODO: change upload of classes?

2019-07-16 15:51 UTC, rossmeier requested changes
[AuD-korr.pdf](https://github.com/latex4ei/Algorithmen-und-Datenstrukturen/files/3397947/AuD-korr.pdf)

2019-07-24 13:10 UTC, HappyDayHunter commented
[corr.pdf.pdf](https://github.com/latex4ei/Algorithmen-und-Datenstrukturen/files/3426929/corr.pdf.pdf)

2019-07-25 20:55 UTC, rossmeier approved these changes

2019-07-25 21:15 UTC, HappyDayHunter commented
[corr.pdf.pdf.pdf](https://github.com/latex4ei/Algorithmen-und-Datenstrukturen/files/3433307/corr.pdf.pdf.pdf)

2019-07-25 21:30 UTC, merged