Update for SS24
latex4ei/Algorithmen-und-Datenstrukturen pull request #6
Opened 2024-08-04 09:44 UTC by dariusptrs

Changes:

- switch f and g in 2.6.1
- add Container + Iteratoren
- update AVL and Heap operations
- update Hashing section

All changes:
[diff.pdf](https://github.com/user-attachments/files/16487033/diff.pdf)

2024-08-04 14:05 UTC, dariusptrs commented on AuD.tex
> +	Hashtabellen sind Felder bei denen die Position eines Objekts durch eine Hashfunktion berechnet wird. Da es zu Kollisionen kommen kann, werden in den Feldern nur Verweise auf eine Liste gespeichert.
nts: Letzten Satz löschen

2024-12-20 12:49 UTC, TimoLass requested changes

2024-12-20 12:49 UTC, TimoLass commented on AuD.tex
> +\textbf{Einfügen:} Einfügen in unterste Ebene, linkste freie Stelle\\
```suggestion
\textbf{Einfügen:} Einfügen in unterste Ebene, linkeste freie Stelle\\
```

2024-12-20 12:51 UTC, TimoLass approved these changes

2024-12-20 12:52 UTC, merged